### ISSUE TITLE
Lets make a distinction between a package and an asset

### ISSUE THREAD

**Issue by emaadali** [JoyceStick-BC/Trimm-CLI#1]
Just an idea...
A user can install an asset, or they can install a collection of assets (a package). So when we are ready to make a release, we package our snatch.json assets into a bundle, and then users can use `snatch install joycestick/packagename`, which downloads all the assets as one large zip.

**Comment by emaadali** [comment]
Of course a user can always use `snatch install joycestick/assetname` if they want to download an individual asset.

**Comment by CoolDude53** [comment]
already handling this
