### ISSUE TITLE
Install assets in a `vendor` folder by default

### ISSUE THREAD

**Issue by emaadali** [JoyceStick-BC/Trimm-CLI#2]
Don't default to current directory. That will get messy. As long as the user is in a project with Snatch, default to installing bundles in `projectroot/vendor`. The user can specify a different folder if they'd like. If a vendor folder doesn't exist, then we will make one.

https://github.com/JoyceStick-BC/Snatch-CLI/blob/570a323cd37ac5e2c74f07ce2682ae7d70e26a05/snatch.py#L9

**Comment by CoolDude53** [comment]
Absolute path to install packages. Defaults to currentDir/Assets/vendor.
