### ISSUE TITLE
Change route

### ISSUE THREAD

**Issue by emaadali** [JoyceStick-BC/Trimm-CLI#3]
Download bundles from `"http://snatch.joycestick.com/api/" + name + "/download"` instead.

https://github.com/JoyceStick-BC/Snatch-CLI/blob/a195e8e2cf1618e54cf1b3912e8c1507160bce5f/snatch.py#L12

**Comment by CoolDude53** [comment]
Done

**Comment by CoolDude53** [comment]
url = "http://snatch.joycestick.com/" + name + "/download"
