### ISSUE TITLE
Pull command details

### ISSUE THREAD

**Issue by CoolDude53** [JoyceStick-BC/Trimm-CLI#5]
Need some detail for how you wish me to implement this:

1.  How will the CLI check with the api for the version of the bundle?
2. How will the CLI handle a newer versioned package? Will it delete the old one and install the new package, or will we check the package's assets and then only reversion the outdated assets? For the latter, what happens when we have new/removed assets in a new version of a package? We'll probably want to download a new info.json when this happens and then check that for new assets to the package.

**Comment by emaadali** [comment]
1. dont worry about it for now
2. dont worry about it for now
